In [1]:
import pandas as pd

df = pd.read_csv("train.csv")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [2]:
print("Number of rows and columns:", df.shape)

Number of rows and columns: (9800, 18)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [4]:
# Checking the number of missing values in each column
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

The Postal Code column contains 11 missing values (approximately 0.11% of the dataset). These values were retained because postal codes are not required for the planned sales analyses, and removing the rows could result in unnecessary data loss.

In [5]:
# Checking the number of duplicate rows
df.duplicated().sum()

0

In [6]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='mixed', dayfirst=False)
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='mixed', dayfirst=False)

df[['Order Date', 'Ship Date']].dtypes

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

In [7]:
df = pd.read_csv("train.csv")

df[['Order Date', 'Ship Date']].head(10)

   Order Date   Ship Date
0  08/11/2017  11/11/2017
1  08/11/2017  11/11/2017
2  12/06/2017  16/06/2017
3  11/10/2016  18/10/2016
4  11/10/2016  18/10/2016
5  09/06/2015  14/06/2015
6  09/06/2015  14/06/2015
7  09/06/2015  14/06/2015
8  09/06/2015  14/06/2015
9  09/06/2015  14/06/2015

In [8]:
df['Order Date'].value_counts().head(10)

Order Date
05/09/2017    38
10/11/2017    35
02/12/2018    34
01/12/2018    34
02/09/2018    33
09/12/2018    33
12/11/2018    30
08/12/2018    30
09/09/2018    29
11/12/2017    28
Name: count, dtype: int64

In [9]:
dates = df['Order Date'].astype(str)

dates[dates.str.split('/').str[0].astype(int) > 12].head(20)

12    15/04/2018
14    22/11/2016
15    22/11/2016
17    13/05/2015
18    27/08/2015
19    27/08/2015
20    27/08/2015
23    16/07/2018
24    25/09/2016
25    16/01/2017
26    16/01/2017
27    17/09/2016
28    17/09/2016
29    17/09/2016
30    17/09/2016
31    17/09/2016
32    17/09/2016
33    17/09/2016
34    19/10/2018
37    27/12/2016
Name: Order Date, dtype: object

In [10]:
df['Order Date'] = pd.to_datetime(
    df['Order Date'],
    format='%d/%m/%Y',
    errors='coerce'
)

df['Ship Date'] = pd.to_datetime(
    df['Ship Date'],
    format='%d/%m/%Y',
    errors='coerce'
)

print("Order Date conversion failed:", df['Order Date'].isna().sum())
print("Ship Date conversion failed:", df['Ship Date'].isna().sum())

Order Date conversion failed: 0
Ship Date conversion failed: 0

In [11]:
print("Earliest Order Date:", df['Order Date'].min())
print("Latest Order Date:", df['Order Date'].max())

print("Total Sales:", df['Sales'].sum())
print("Average Order Value:", df['Sales'].mean())

Earliest Order Date: 2015-01-03 00:00:00
Latest Order Date: 2018-12-30 00:00:00
Total Sales: 2261536.7827000003
Average Order Value: 230.7690594591837

In [12]:
# Which product category generates the highest sales?
sales_by_category = (
    df.groupby('Category')['Sales']
    .sum()
    .sort_values(ascending=False)
)

print(sales_by_category)

Category
Technology         827455.8730
Furniture          728658.5757
Office Supplies    705422.3340
Name: Sales, dtype: float64

In [13]:
# Which product generates the highest sales?
sales_by_product = (
    df.groupby('Product Name')['Sales']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print(sales_by_product)

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

In [14]:
# Which region generates the highest total sales?
sales_by_region = (
    df.groupby('Region')['Sales']
    .sum()
    .sort_values(ascending=False)

)

print(sales_by_region)

Region
West       710219.6845
East       669518.7260
Central    492646.9132
South      389151.4590
Name: Sales, dtype: float64

In [15]:
#How do total sales change from year to year?
df['Year'] = df['Order Date'].dt.year

sales_trend_by_year = (
    df.groupby('Year')['Sales']
    .sum()
    .sort_index()
)

print(sales_trend_by_year)

Year
2015    479856.2081
2016    459436.0054
2017    600192.5500
2018    722052.0192
Name: Sales, dtype: float64

In [16]:
#Year-over-Year Growth atau YoY Growth)
sales_trend_by_year = df.groupby('Year')['Sales'].sum().sort_index()

sales_growth = sales_trend_by_year.pct_change() * 100

print(sales_growth)

Year
2015          NaN
2016    -4.255484
2017    30.636812
2018    20.303396
Name: Sales, dtype: float64

**Year-over-Year Sales Growth Analysis**

Total sales declined by 4.26% in 2016 compared to 2015. However, sales recovered significantly in 2017, increasing by 30.64% compared to the previous year. In 2018, sales continued to grow by 20.30%, reaching the highest annual sales total during the 2015–2018 period.

Although the sales growth rate slowed in 2018, overall sales continued to increase. The highest growth rate occurred in 2017, while the highest total sales were recorded in 2018.

In [17]:
#Which month generates the highest total sales?
df['Month'] = df['Order Date'].dt.month

sales_trend_by_month = (
    df.groupby('Month')['Sales']
    .sum()
    .sort_values(ascending=False)
)

print(sales_trend_by_month)

Month
11    350161.7110
12    321480.1695
9     300103.4117
10    199496.2947
3     197573.5872
8     157315.9270
5     154086.7237
6     145837.5233
7     145535.6890
4     136283.0006
1      94291.6296
2      59371.1154
Name: Sales, dtype: float64

**Monthly Sales Analysis**

November recorded the highest total sales at 350,161.71, followed by December at 321,480.17. In contrast, February had the lowest total sales at 59,371.12.

The results show that total sales were concentrated toward the end of the year, particularly in November and December. However, further analysis is needed to determine the factors behind this pattern.

In [18]:
#Which product category has the highest average sales per order?
sales_by_category = (
    df.groupby('Category')['Sales']
    .mean()
    .sort_values(ascending=False)
)

print(sales_by_category)

Category
Technology         456.401474
Furniture          350.653790
Office Supplies    119.381001
Name: Sales, dtype: float64

### Average Sales by Product Category

Technology recorded the highest average sales per transaction at 456.40, followed by Furniture at 350.65. Office Supplies had the lowest average sales at 119.38.

The average sales value for Technology was approximately 3.82 times that of Office Supplies. This suggests that Technology products generated a higher average sales value per transaction than the other categories.

In [19]:
#Which customer segment generates the highest total sales?
sales_by_segment = (
    df.groupby('Segment')['Sales']
    .sum()
    .sort_values(ascending=False)
)

print(sales_by_segment)

Segment
Consumer       1.148061e+06
Corporate      6.884941e+05
Home Office    4.249822e+05
Name: Sales, dtype: float64

### Sales by Customer Segment

The Consumer segment generated the highest total sales at approximately 1.15 million, followed by Corporate at 688,494.10 and Home Office at 424,982.20.

Consumer sales were approximately 2.7 times higher than Home Office sales. This indicates that the Consumer segment contributed the largest share of total sales among the three customer segments.

In [20]:
#Which 10 states generate the highest total sales?
sales_by_states = (
    df.groupby('State')['Sales']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print(sales_by_states)

State
California      446306.4635
New York        306361.1470
Texas           168572.5322
Washington      135206.8500
Pennsylvania    116276.6500
Florida          88436.5320
Illinois         79236.5170
Michigan         76136.0740
Ohio             75130.3500
Virginia         70636.7200
Name: Sales, dtype: float64

### Top 10 States by Sales

California recorded the highest total sales at 446,306.46, followed by New York at 306,361.15 and Texas at 168,572.53.

California's total sales were approximately 1.46 times those of New York and 6.3 times those of Virginia, which ranked tenth among the top 10 states.

These findings show that California contributed the highest sales among the states analyzed. Further analysis of sales by product category and customer segment could help identify the factors behind this performance.

In [21]:
#What is the average shipping duration in days?
shipping_duration = (
    df['Ship Date'] - df['Order Date']
).dt.days.mean()

print(shipping_duration)

3.9611224489795918

### Average Shipping Duration

The average shipping duration was approximately 3.96 days per transaction row, calculated as the difference between the order date and the ship date.

Further analysis is needed to examine the distribution of shipping durations and calculate the average duration per unique order, since a single order may contain multiple transaction rows.

In [27]:
#How short or long can the shipping duration be?
shipping_duration = (
df['Ship Date'] - df['Order Date']
).dt.days

shortest_shipping_duration = shipping_duration.min()
longest_shipping_duration = shipping_duration.max()
median_shipping_duration = shipping_duration.median()

print("Shortest shipping duration:", shortest_shipping_duration)
print("Longest shipping duration:", longest_shipping_duration)
print("Median shipping duration:", median_shipping_duration)

Shortest shipping duration: 0
Longest shipping duration: 7
Median shipping duration: 4.0

The shipping duration ranged from 0 to 7 days, with a median of 4 days. Some orders were shipped on the same day they were placed, while the median indicates that half of the transaction rows had a shipping duration of 4 days or less. Further analysis is needed to calculate the average shipping duration per unique order, as a single order may contain multiple transaction rows.

In [29]:
df['Shipping Duration'] = (
    df['Ship Date'] - df['Order Date']
).dt.days

df.groupby('Order ID')['Shipping Duration'].nunique().value_counts()

Shipping Duration
1    4922
Name: count, dtype: int64

In [31]:
df['Shipping Duration'] = (
df['Ship Date'] - df['Order Date']
).dt.days

shipping_duration_by_order = (
df.groupby('Order ID')['Shipping Duration'].first()
)

average_shipping_duration_by_order = (
shipping_duration_by_order.mean()
)

print(average_shipping_duration_by_order)

3.958553433563592

In [36]:
df.groupby('Ship Mode')['Shipping Duration'].mean().sort_values()

Ship Mode
Same Day          0.044610
First Class       2.179214
Second Class      3.249211
Standard Class    5.008363
Name: Shipping Duration, dtype: float64

In [40]:
df.groupby('Ship Mode')['Order ID'].nunique()

Ship Mode
First Class        772
Same Day           261
Second Class       944
Standard Class    2945
Name: Order ID, dtype: int64

**Order Distribution by Ship Mode**

Standard Class accounted for the largest share of orders, with 2,945 unique orders (59.83% of all orders). Second Class followed with 944 orders (19.18%), while First Class recorded 772 orders (15.69%). Same Day had the fewest orders, totaling 261 (5.30%).

Combined with the shipping duration analysis, Standard Class had the longest average shipping duration at approximately 5.01 days, while Same Day had the shortest at approximately 0.04 days. Further analysis would be needed to understand the factors influencing customers' shipping method choices.

In [45]:
#Which customers generated the highest total sales?
sales_by_customers = (
    df.groupby('Customer Name')['Sales']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print(sales_by_customers)

Customer Name
Sean Miller           25043.050
Tamara Chand          19052.218
Raymond Buch          15117.339
Tom Ashbrook          14595.620
Adrian Barton         14473.571
Ken Lonsdale          14175.229
Sanjit Chand          14142.334
Hunter Lopez          12873.298
Sanjit Engle          12209.438
Christopher Conant    12129.072
Name: Sales, dtype: float64

**Top 10 Customers by Sales**

Sean Miller generated the highest total sales at 25,043.05, followed by Tamara Chand at 19,052.22 and Raymond Buch at 15,117.34. Sean Miller's total sales were approximately 31.4% higher than those of Tamara Chand.

This analysis identifies the customers contributing the highest sales values during the dataset period. Further analysis of order frequency and average order value could provide additional insights into customer purchasing behavior.

In [54]:
customer_analysis = (
    df.groupby('Customer Name').agg(
        Total_Sales=('Sales', 'sum'),
        Total_Orders=('Order ID', 'nunique')
    )
    .sort_values('Total_Orders', ascending=False)
    .head(10)
)

print(customer_analysis)

                     Total_Sales  Total_Orders
Customer Name
Emily Phan             5478.0608            17
Chloris Kastensmidt    3154.8550            13
Joel Eaton             6760.8150            13
Zuschuss Carroll       8025.7070            13
Patrick Gardner        3086.9070            13
Pete Kriz              8646.9340            12
Ken Black              2744.7420            12
Henry Goldwyn          3247.6420            12
Clay Ludtke           10880.5460            12
Bill Donatelli         5718.5210            12

In [59]:
total_sales_customer =(
    df.groupby('Customer Name')['Sales'].sum()
)

total_sales_dataset = df['Sales'].sum()

sales_contribution = (total_sales_customer / total_sales_dataset) *100

top_10_sales_contribution = (
    sales_contribution
    .sort_values(ascending=False)
    .head(10)
)

print(top_10_sales_contribution)

Customer Name
Sean Miller           1.107347
Tamara Chand          0.842446
Raymond Buch          0.668454
Tom Ashbrook          0.645385
Adrian Barton         0.639988
Ken Lonsdale          0.626796
Sanjit Chand          0.625342
Hunter Lopez          0.569228
Sanjit Engle          0.539874
Christopher Conant    0.536320
Name: Sales, dtype: float64

In [41]:
df.head(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Year,Month,Shipping Duration
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2017,11,3